# Generated by Django 4.1.7 on 2023-05-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ImageField(default=None, upload_to='home/%Y/%m'),
        ),
    ]
