# Generated by Django 4.1.7 on 2023-05-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_category_remove_product_orther_customer_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_closed', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200, null=True)),
                ('keyword', models.CharField(max_length=50)),
            ],
        ),
    ]
